### PR TITLE
Update neighbour.py

### PR DESCRIPTION
**Pull request by jkkwon83**
prevent infinity loop

### CODE REVIEW

**Comment by jkkwon83** [comment]
some zigbee device (Dawon SmartPlug PM-B430-ZB) is not equal "sum of len(neighbors)", "val.Entries"

**Comment by Adminiuga** [comment]
can you send me a debug log of scanning such a device? I just want to better understand its behavior.

**Comment by jkkwon83** [comment]
debug log
[log.txt](https://github.com/zha-ng/zha-map/files/4049450/log.txt)

**Comment by Adminiuga** [comment]
@jkkwon83 do you still have this plug? Can you send me the log after the patch?
In other words I'm trying to see if after a response with an empty neighbor list, does it have any other entries with information?

**Pull request merged**
